//用户
const SET_USER_INFO = 'SET_USER_INFO'
const CLEAR_USER_INFO = 'CLEAR_USER_INFO'
const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
export const USER = {
  SET_USER_INFO,
  CLEAR_USER_INFO,
  UPDATE_USER_INFO,
}
